start = events
events = element events {track+}
track = element track {attribute type { xsd:integer }, name, event+}

# start event schema
name = attribute name {"early" | "mid" | "late"}
event = element event {title, date+, description, lat*, lon*, media*}
title = element title {text}

# date schema
date = element date {attribute type { "start" | "end" }, year*, month*, day*, era*}
year = element year {xsd:integer}
month = element month {xsd:integer}
day = element day {xsd:integer}
era = element era {text}

# event contin. 
description = element description {text}
lat = element lat {xsd:float}
lon = element lon {xsd:float}
media = element media {xsd:anyURI}
